name: widget_gen
description: A Flutter Code Gen Package Used to Generate Widgets for WidgetStudio
version: 1.0.1+3
homepage: https://github.com/rodydavis/widget_gen
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  shortid: ^0.1.1
  source_gen: ^0.9.5
  build: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_version: ^2.0.1

flutter:
  uses-material-design: true
